site_name: IDSA Knowledge Base
# site_url: http://KnowledgeBase.internationaldataspaces.org
# repo_url: https://github.com/International-Data-Spaces-Association/idsa
repo_url: https://github.com/ssteinbuss/idsa
site_description: The IDSA Knowledge Base
docs_dir: how-to-build-data-spaces
# site_dir: html
theme: readthedocs
#extra_css: ["https://www.fiware.org/style/fiware_readthedocs.css", "https://www.fiware.org/style/fiware_readthedocs_security.css"]
use_directory_urls: false
markdown_extensions:
  - admonition
#google_analytics: ['UA-******', 'fiware-idm.readthedocs.io']
pages:
  - Home: 'README.md'
  - Gather Knowledge: '1-Gather-Knowledge.md'
  - Define your use case: '2-Define-Your-Use-Case.md'
  - Build Components: '3-Build-Components.md'
    - Roles in Certification: 'Roles-in-Certification.md'
  - Prepare for go live: '4-Prepare-for-Go-Live.md'
  - Share: 'Share.md'
